<a href="https://colab.research.google.com/github/ashah1308/LoanStatusPrediction/blob/main/Numpy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
list1 = [1,2,34, 5]

In [2]:
print(list1)

[1, 2, 34, 5]


In [3]:
!pip install numpy


In [4]:
#numpy arrary must have same data type

In [7]:
#ndarray = n- dimensional array
import numpy as np
np1 = np.array([0,1,2,3,4,5])
print(np1)

[0 1 2 3 4 5]


In [8]:
np1.shape

(6,)

In [11]:
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#step

In [13]:
#steps
np3 = np.arange(0,10,3)
print(np3)

[0 3 6 9]


In [17]:
#zeros
np4 = np.zeros(9)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
# Multidimensional Array
np5 = np.zeros((2,3))
print(np5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# Full
np7 = np.full((10),6)
print(np7)

[6 6 6 6 6 6 6 6 6 6]


In [31]:
#multidimensinal Full
np8 = np.full((4,4), 40)
print(np8)

[[40 40 40 40]
 [40 40 40 40]
 [40 40 40 40]
 [40 40 40 40]]


In [36]:
# Convert python list to numpy
my_list = [[1,2,3,4,5],[1,2,3,4,5]]
np9 = np.array([[1,2,3,4],[5,6,7,8]])
print(np9)
np9.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [48]:
#Slicing Numpy Array
np11 = np.array([1,2,3,4,5,6,7,8,9])
#return 2,3,4,5
print(np11[1:5])
#return 1,2,3
print(np11[:3])
# return 7 ,8, 9
print(np11[6:])
#return negative slice
# 7, 8
print(np11[-3:-1])
#return slice with steps
print(np11[1:5])
print(np11[1:9:2])

#step on entire array
print(np11[::2])

[2 3 4 5]
[1 2 3]
[7 8 9]
[7 8]
[2 3 4 5]
[2 4 6 8]
[1 3 5 7 9]


In [51]:
# Slice 2D array
np2d = np.array([
    [1,2,3,4,5],
     [6,7,8,9,10]])
print(np2d[1,0])

6


In [56]:
print(np2d[0:2,2:])

[[ 3  4  5]
 [ 8  9 10]]


In [65]:
# Universal Function in Numpy
print(np11)
#[1 2 3 4 5 6 7 8 9]
#Square Root
#print(np.sqrt(np11))
print(np.max(np11))
print(np.min(np11))


# absolute Va
npabs = np.array([-1,-2,-3, 4, 5])
print(np.abs(npabs))

#find sign
print(np.sign(npabs))

# similary for sin , log





[1 2 3 4 5 6 7 8 9]
9
1
[1 2 3 4 5]
[-1 -1 -1  1  1]


In [66]:
# https://numpy.org/doc/stable/reference/ufuncs.html





In [67]:
# Copy Vs View of np Array

In [71]:
np1 = np.array([0,1,2,3,4,5])
np2 = np1.view()
print(f'Original Np1 {np1}')
print(f'Original Np2 {np2}')

np1[0] = 90

print(f'Change Np1 {np1}')
print(f'Original Np2 {np2}')

Original Np1 [0 1 2 3 4 5]
Original Np2 [0 1 2 3 4 5]
Change Np1 [90  1  2  3  4  5]
Change Np2 [90  1  2  3  4  5]


In [73]:
# Create a copy

np2 = np1.copy()
print(f'Original Np1 {np1}')
print(f'Original Np2 {np2}')

np1[0] = 40
np2[3] = 23
print(f'Change Np1 {np1}')
print(f'Original Np2 {np2}')

Original Np1 [40  1  2  3  4  5]
Original Np2 [40  1  2  3  4  5]
Change Np1 [40  1  2  3  4  5]
Original Np2 [40  1  2 23  4  5]


In [83]:
# Shape Reshape
# Create 1-2 Numpy array and get shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np4=np1.reshape(2,3,2)
print(np4.reshape(-1))

# create 2D
np2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(np2)
np2.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [92]:
# Iterating array

np1 = np.array([1,2,3,4,5,6,7,8,9,10])
# for x in np1:
#   print(x)

np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# for row in np2:
#   for col in row:
#     print(col)

np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# for z in np3:
#   for y in z:
#     for x in y:
      # print(x)

# Use np.nditer()
for x in np.nditer(np3):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [96]:
# sorting numpy arrays numerical
np1 = np.array([6,7,9,1,2,5])
print(np.sort(np1))

#alpha
np2 = np.array(["john","aakash", "parth", "Ankit"])
print(np.sort(np2))

#bool
np3 = np.array([True,False, False, True])
print(np.sort(np3))


np4 = np.array([[10,20,30,14,45],[6,7,8,9,10]])
print(np.sort(np4))


[1 2 5 6 7 9]
['Ankit' 'aakash' 'john' 'parth']
[False False  True  True]
[[10 14 20 30 45]
 [ 6  7  8  9 10]]


In [106]:
# Searching in numpy Array #return index no
np1 = np.array([6,7,9,1,2,5,8,2,5])
x = np.where(np1 == 2) # return index no
# print(np1)
# print (x[0])
# print(np1[x[0]])
y = np.where(np1 % 2 == 0)
print(np1[y[0]])

[6 2 8 2]


In [115]:
# How Filter numpy Array
np1 = np.array([7,9,1,2,5,8,2,5])
# x = [True, False, True ,False,True, False, True ,False]
# print(np1)
# print(np1[x])
filtered = []
for thing in np1:
  if thing > 5:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1[filtered])

[7 9 8]


In [117]:
#Filter short cut
filter = np1 % 2 == 0
print(np1[filtered])

[7 9 8]
